### ISSUE TITLE
Ambee sensor werkt ineens niet meer

### ISSUE THREAD

**Issue by DavyRoswinkel** [huizebruin/Home-Assistant-Config#2]
Hey, bedankt voor het werk aan deze sensor, vind hem geweldig.
Enige probleem is, sinds een paar dagen werkt hij niet meer, eerder werkte hij wel.

Nu blijft alles op onbekend staan en op 0/m2.
Ik heb al een paar keer de code en de sensor verwijderd en opnieuw toegevoegd.
Heb de code precies geknipt en geplakt.

Via postman, krijg ik wel de juiste gegevens. ( dus de ambee link en api kloppen)
In de logfile vond ik:
 Logger: homeassistant.helpers.template
Source: helpers/template.py:1367
First occurred: 22:51:43 (6 occurrences)
Last logged: 22:51:43

    Template variable warning: 'None' has no attribute 'tree_pollen' when rendering '{{ state_attr('sensor.pollen', 'Count')['tree_pollen'] }}'
    Template variable warning: 'None' has no attribute 'weed_pollen' when rendering '{{ state_attr('sensor.pollen', 'Count')['weed_pollen'] }}'
    Template variable warning: 'None' has no attribute 'grass_pollen' when rendering '{{ state_attr('sensor.pollen', 'Count')['grass_pollen'] }}

en 

Logger: homeassistant.components.sensor
Source: core.py:896
Integration: Sensor (documentation, issues)
First occurred: 22:49:56 (2 occurrences)
Last logged: 22:49:56

Error adding entities for domain sensor with platform rest
Error while setting up rest platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 558, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 581, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 460, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1208, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 896, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.pollen. State max length is 255 characters.

Meer mensen hier last van??? Iemand een oplossing?

**Comment by huizebruin** [comment]
klopt ik heb er nu ook last van sinds een paar dagen,
we zijn aan het kijken of we het op kunnen lossen.

**Comment by ramakersr** [comment]
Het probleem is opgelost

**Comment by DavyRoswinkel** [comment]
Ja het werkt weer. Thanx!
